quotes = [
 { author: "Ryan Gibbons", company: "Senior Developer, Warren Douglas", text: "I feel you were a great instructor. The presentation, your control, and the overall presentation were great. I feel that class had enough freedom to explore different things, but was still grounded with a plan of attack. Very easy to listen for 6 hours today; can't say that with every instructor. Overall I would give this course and you very high marks." },
 { author: "Nate Schutta", company: "Software Architect and Author of Foundations of Ajax", text: "Want to learn more about git? Look no further than @matthewmccull - his Git Foundations class rocks, outstandingly good!" },
 { author: "David Bock", company: "Founder, Code Sherpas", text: "Online git training today was phenomenal. Highly recommended." },
 { author: "Brad Armstrong", company: "Digital River", text: "Fantastic Git training with @matthewmccull today, a really polished pro. Get in on the next one!" },
 { author: "Brad Haydon", company: "Oakley, Inc.", text: "When Oakley decided to use Git as its primary version control system, training was a huge concern of ours. In an extremely short amount of time, Scott had our developers up and running, with absolutely no issues at all." },
 { author: "Bruce Tate", company: "President of RapidRed", text: "Matthew, this class was truly excellent. It may be the best online class I've ever attended. What you did is not easy with that tool suite, but you make it look so." },
 { author: "Josh Long", company: "Developer Evangelist, SpringSource", text: "Matthew McCullough did a fantastic job during today's GitHub training! Highly recommended!" },
 { author: "Daniel Moroz", company: "Student Organizer, PennApps", text: "Of the 20 or so talks we had at PennApps, John's was the most lucid. He taught even advanced users new features while making sure that inexperienced folks didn't fall behind." },
 ];