auto: true
server: true
exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor, gems]
gauges_id: 50235916613f5d4f9c000042
google_analytics_id: UA-3769691-19

# For Atom Feed
domain: training.github.com
author: GitHub Training Team
email: training@github.com
title: GitHub Training
