#!/bin/sh

set -e
export CC=gcc

echo "==> Installing gem dependencies…"

mkdir -p vendor/gems
bundle install --binstubs bin --path vendor/gems

echo "==> Cloning into submodules"
git submodule init
git submodule update
